### ISSUE TITLE
NullPointerException on enable

### ISSUE THREAD

**Issue by PC1up** [SimonPlays15/BetterBanSystem#1]
The following exceptions happens when enabling the plugin:
```[20:46:55 ERROR]: [BetterBanSystem] [BetterBanSystem] [ERROR] plugins\BetterBanSystem\uuids.bin (Das System kann den angeg...
[20:46:55 ERROR]: [BetterBanSystem] [BetterBanSystem] [ERROR] Failed to initialize BetterBanSystem:
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.io.IOException.getCause()" is null
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.core.logging.GlobalLogger.log(GlobalLogger.java:320)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.core.logging.GlobalLogger.error(GlobalLogger.java:274)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.api.uuid.UUIDFetcher.saveUUIDToBin(UUIDFetcher.java:62)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.api.uuid.UUIDFetcher.loadUsercacheJson(UUIDFetcher.java:50)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.core.BetterBanSystem.<init>(BetterBanSystem.java:215)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.spigot.SpigotCore$1.<init>(SpigotCore.java:21)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.spigot.SpigotCore.onEnable(SpigotCore.java:21)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1016)
        at org.bukkit.Bukkit.reload(Bukkit.java:909)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
        at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:510)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:1583
[20:46:55 ERROR]: Error occurred while enabling BetterBanSystem v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.io.IOException.getCause()" is null
        at me.github.simonplays15.betterbansystem.core.logging.GlobalLogger.log(GlobalLogger.java:320) ~[BetterBanSystem-1.0.jar:?]
        at me.github.simonplays15.betterbansystem.core.logging.GlobalLogger.error(GlobalLogger.java:274) ~[BetterBanSystem-1.0.jar:?]
        at me.github.simonplays15.betterbansystem.spigot.SpigotCore.onEnable(SpigotCore.java:38) ~[BetterBanSystem-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1016) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

I tried in 1.20.4 and 1.18.2. Both servers were running PaperSpigot.

This is the exception that happens on start, since the one above was after a reload:
```
[20:46:41 ERROR]: [BetterBanSystem] [BetterBanSystem] [ERROR] plugins\BetterBanSystem\uuids.bin (Das System kann den angeg...
[20:46:41 ERROR]: [BetterBanSystem] [BetterBanSystem] [ERROR] Failed to initialize BetterBanSystem:
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.io.IOException.getCause()" is null
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.core.logging.GlobalLogger.log(GlobalLogger.java:320)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.core.logging.GlobalLogger.error(GlobalLogger.java:274)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.api.uuid.UUIDFetcher.saveUUIDToBin(UUIDFetcher.java:62)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.api.uuid.UUIDFetcher.loadUsercacheJson(UUIDFetcher.java:50)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.core.BetterBanSystem.<init>(BetterBanSystem.java:215)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.spigot.SpigotCore$1.<init>(SpigotCore.java:21)
        at BetterBanSystem-1.0.jar//me.github.simonplays15.betterbansystem.spigot.SpigotCore.onEnable(SpigotCore.java:21)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:1583
[20:46:41 ERROR]: Error occurred while enabling BetterBanSystem v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.io.IOException.getCause()" is null
        at me.github.simonplays15.betterbansystem.core.logging.GlobalLogger.log(GlobalLogger.java:320) ~[BetterBanSystem-1.0.jar:?]
        at me.github.simonplays15.betterbansystem.core.logging.GlobalLogger.error(GlobalLogger.java:274) ~[BetterBanSystem-1.0.jar:?]
        at me.github.simonplays15.betterbansystem.spigot.SpigotCore.onEnable(SpigotCore.java:38) ~[BetterBanSystem-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by SimonPlays15** [comment]
After looking up the error it seems to that the filehandler for the Logging System because it cannot configure the FileHandler.

Is in the config.yml the value of "logging.logfiles" set to true or false?

**Comment by PC1up** [comment]
The plugin created no folder and no config.yml.

**Comment by SimonPlays15** [comment]
After testing to start the plugin on a PaperSpigot 1.20.4 Server on my local machine everthing works fine.
On what platform are you running the server? It can be that the Server itself is missing the write permissions for files.

**Comment by SimonPlays15** [comment]
For safety I make some changes to the code so the error should not be printed anymore. It can happen that an error gets thrown but this would not interrupt the plugin in the enable process.

Let me know if everything works after the patch =)

**Comment by SimonPlays15** [comment]
After some time I guess the Bug should be gone and everything is working fine?
If not please open a new issue.
